### ISSUE TITLE
exist in modules not working properly

### ISSUE THREAD

**Issue by zxlame** [z00m128/sjasmplus#177] opened 2022-05-05 17:00 UTC
main.a80
```
			device	zxspectrum128'
			org	0x8000
start
			di
			halt
mod1.l1			equ	data
			include	"mod1.a80"
data			ds	1
			display mod1.l1
			display mod1.l2
			savesna	"main.sna", start
```
mod1.a80
```
			module	mod1
			db	1
			if not exist mod1.l1
l1			ds	1
			endif
			if not exist mod1.l2
l2			ds	1
			endif
			endmodule
```
output
```
SjASMPlus Z80 Cross-Assembler v1.19.0 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
main.a80(6): warning: Label has different value in pass 3: previous value 32772 not equal 32771
> 0x8003
> 0x8003
Pass 3 complete
Errors: 0, warnings: 1, compiled: 18 lines, work time: 0.015 seconds
```
mod1.l1 equal mod1.l2 ??? ignoring ds in "if" but makes labels

**Comment by ped7g** [comment] 2022-05-06 21:11
Been thinking about this for few hours, and now I'm pretty sure this works "as intended", I don't see any good way how to modify the behaviour.

Any idea I tried breaks some other use case which feels also logical, so I guess this is just how multi-pass assembler works, the symbols are preserved across, so defining symbol already in first pass will cause `exist` to return different value in next pass. I was unable to formulate any simple rule, when the `exist` would be some exception and how to do it.

Will keep this open for another day or two just in case I have some new idea, but at this moment this is not-a-bug, and nothing to fix in sjasmplus, and will be closed in next days.

**Closed** 2022-05-08 09:20 UTC
Labels: bug, not a bug, RFC
