### ISSUE TITLE
Cannot use LUA inside MACRO

### ISSUE THREAD

**Issue by Liniya** [z00m128/sjasmplus#46] opened 2019-04-08 06:24 UTC
This is a fairly old one that is also present in the base 1.07RC7 ver. Attempting to use LUA inside a macro produces various unrelated errors concerning LUA/ENDLUA.
Sample code:

```
	MACRO luatest
	 LUA
	  sj.warning('Macro LUA test')
	 ENDLUA
	ENDM

	luatest

```

Console output:
```
SjASMPlus Z80 Cross-Assembler v1.11.1 (https://github.com/z00m128/sjasmplus)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
luatest.asm(8): error: [LUA] Unexpected end of lua script
luatest.asm(8): error: Unrecognized instruction: sj.warning('Macro LUA test')

luatest.asm(8): error: [ENDLUA] End of lua script without script
Pass 3 complete
Errors: 3, warnings: 0, compiled: 6 lines, work time: 0.000 seconds
```

**Comment by ped7g** [comment] 2019-04-08 07:18
just made me thinking... can you produce macro from LUA? Does it work?
If yes, then this is of very low priority, it's still a bug, but if you need it, you can just do the other thing, prepare in the LUA the final macro, and use the macro where needed... If there's too much dynamics to do create proper single macro, maybe consider writing whole thing in LUA in the first place.

Overall my internal focus is to rather get macro language of sjasmplus into shape and power, to avoid LUA completely ... not that I dislike it, but LUA is complete and functional thing, you can even drop sjasmplus completely and just write pure LUA script generating simple ASM file (Martin B. just recently did something similar for his "Regression" demo, although he's generating asm not from Lua, but from node.js scripts)... but once you have ASM file, you need a reliable assembler, so that's why I'm focusing first on the sjasmplus internals, fixing Lua things if I spot them and they will be simple to fix.. (I have actually idea what is happening in this case, but don't want to dig into it with current parser architecture, I'm still considering full rewrite of it).

**Comment by Liniya** [comment] 2019-04-08 08:01
Do you mean something like defining a macro with _pl(" MACRO mac arg1") and whatnot line by line inside a LUA..ENDLUA block? In my case, the point was rather to do some additional parsing of the macro arguments using LUA, so I don't think this will work. Well, at least it's good to know that this is indeed a bug and not some kind of internal incompatibility that prevents this sort of usage.

**Comment by ped7g** [comment] 2019-04-08 08:43
It doesn't matter how you call it (bug or internal incompatibility)... the point is, that the documentation about `LUA` directive does not even mention any issue with MACRO/DUP/etc.., so if you follow the documentation, and it does not produce expected results, it's a "bug" IMO. It may be nasty bug requiring lot of effort to fix ("internal incompatibility" thing :D ), but still bug.
So I'm glad you reported it, it's good to have all the bugs at least documented... (I also think the LUA part is unusable in DUP-EDUP blocks, and may be also inside IF/ENDIF blocks, as some of those use a bit different parser paths and internal assembler state is implemented by "many globals", so it's kinda way too simple for one of those parser variants to do things a bit differently and being unable to parse LUA-ENDLUA blocks correctly). There may be even some deeper problem about keeping lua-context in good shape, but hard to tell, before I would dig into it, and debug it properly.

I'm pretty sure the initial error reported by you is simple parsing problem (the LUA block starts, but doesn't get feed from macro-lines feeder, so it sees "end of source" right after the LUA directive). If I would fix that, maybe some other nasty things would appear... :D

**Comment by ped7g** [comment] 2019-04-08 09:21
thinking about it a bit more... so the macro is injected at the place of its usage, with actual arguments... so there the new LUA-ENDLUA block would be injected, each pass, with hopefully same/similar arguments (you can probably limit it to PASS3 to parse only final arguments, like label values/etc), then he lua script would parse the values and emit something, maybe instructions, all of this still in-place of macro usage... Sounds quite OK to me (as long as not inside dynamic (between passes) IF-ENDIF, or DUP-EDUP blocks, which would both add extra layer of internal magic with global state = more things to break) And as long as you would not define something global with it (to create duplicity problems in case of that macro used on multiple places).

May be I will take a look sooner than I expected, as this may be actually easy to fix and it may cover the simpler use cases, like truly only parsing arguments and emitting instructions... But if you have more dynamic usage on mind, consider writing whole blocks in LUA, like I did in some tests/z80 tests (before the macro system was fixed enough to provide functionality I did need for those ... you can actually compare the LUA vs macro versions, to see how it is evolving). But my focus is rather 80:20 focused toward non-Lua things, to make the assembler more stable and powerful in its base form.

There was also some issue requesting "exp" function, which ended being resolved with LUA script, but the author hit some problem with EDUP, so he had to write whole loop inside Lua, IIRC...

**Comment by Liniya** [comment] 2019-04-08 14:42
Personally in this instance I need a way to tell between labels and 'non-labels' in a macro input argument. Or perhaps I should say, a way to tell if the input can be 'safely feed to IFUSED'. :) At the minimum, this entails telling whether the first character of the input is allowed in labels, or a similar operation, which I don't think you can do easily in Sjasmplus other than resorting to LUA. There are ways around it but they don't integrate well with the module/label system. So yep, I'd quite appreciate that.

Another reason one might want to do this is because LUA inlining in Sjasmplus doesn't lend itself well towards quick usage, with a minimum of _three_ lines necessary to run a single LUA statement. So for instance if you want to define a LUA function which you intend to use often, that likely wouldn't look well in the source so you might want to wrap it in a macro for convenience, even if it doesn't involve argument-parsing and such.

**Closed** 2019-04-11 06:53 UTC
Labels: bug

**Comment by ped7g** [comment] 2019-04-11 07:00
Liniya: the parsing is fixed, and somewhat modified test works for me (see `tests/macros/issue46_LuaInsideMacro.asm`).

But I actually don't see how you will check if macro input is label or not label by lua, would be interested to see example if you somehow manage it, either I'm missing some detail about how macro argument substitution works, or I'm afraid there's currently no Lua interface capable to operate with macro arguments at that detail?

About `IFUSED` issue in particular ... maybe some operator `islabel(expression)` would be better in this particular case... I have in my TODO one line about expanding operators to be capable also to partially process strings/etc, doing some type/expression checks sounds as reasonable addition to that, but I have no timeframe for those, it's currently just "idea" in head.

**Comment by Liniya** [comment] 2019-04-11 13:14
Great!

About checking for labels: as long as macro argument substitution works inside LUA blocks, I suppose one could write a parser in LUA to analyze the input much in the way Sjasm itself does it. Logically it's not the same thing as checking 'whether Sjasm itself considers string S to be a label', but it could work on practice. However, my actual use case is much simpler than having to analyze input expressions of arbitrary length/complexity. It's mostly about what you can and can't feed to IFUSED, and the input can only be a purely-numeric expression or a single label (with an optional '+1' at the end). These things can be checked for with a couple of operations in LUA.

**Comment by ped7g** [comment] 2019-04-11 14:25
I don't think the substitution will touch the content of LUA-ENDLUA block, that would really surprise me. I even think it makes most sense to keep it like this, as the defines/macro values are assembly related, and if they would substitute some part of lua script by accident, it would be very unintuitive to the coder.

I would rather expect in such situation some function for Lua interface, like `sj.getMacroArgument("arg0")` which would return string containing the current macro argument, that seems like more "logical" or "least surprising" behaviour IMHO. But there's no such interface as far as I can tell. ... actually, there's `get_define` ... one can probably `define` some hardcoded symbol in ASM with value from argument, and then read that in lua... it's kinda very cumbersome, but ok, now I'm starting to think it may be actually possible.

**Comment by Liniya** [comment] 2019-04-11 14:47
Oh. I wondered about this, but I somehow assumed from earlier discussion that it won't be making a distinction, and replace the macro arguments inside LUA blocks just as well. So that e.g. something like the following works in LUA:

```
	 local mystr = [[
arg0
]]
```

If not, then indeed a specialized LUA function to get a macro argument would be handy there. Although as you say it should be possible to work around this using DEFINEs in the meantime.

**Comment by Liniya** [comment] 2019-04-11 15:50
In fact, if it works similarly to DEFINE substitutions, then perhaps something like this could work, eliminating the need for a specialized inbuilt function:

```
	LUA
	 function getMacroArgument(argname)
	  _pl(" DEFINE _LUA_GET_MACRO_ARGUMENT "..argname)
	  local result = sj.get_define("_LUA_GET_MACRO_ARGUMENT")
	  _pl(" UNDEFINE _LUA_GET_MACRO_ARGUMENT")
	  return result
	 end
	ENDLUA

;simulating a macro argument with a DEFINE here
;
	DEFINE MACRO_ARG0 testasdf

;this returns 'testasdf'
;
	LUA
	 sj.warning(getMacroArgument("MACRO_ARG0"))
	ENDLUA
```

One thing I'm not sure about, and something this would depend on I suppose, is how it treats calling a custom LUA function (defined elsewhere) in a macro, e.g. whether it's still considered the same context and such.

**Comment by ped7g** [comment] 2019-04-11 17:27
Well, I really didn't expect this one to "just work", but it does, check the commit for your example.

The Lua context ("state") is global through whole assembling and through all passes, so if you are just defining function, it's enough to enclose that into PASS1 block, no need to redefine it any more, and it will be visible in every other LUA block.
