### ISSUE TITLE
savetap creating BASIC listing with incorrect memory location values

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [z00m128/sjasmplus#109] opened 2020-06-12 05:12 UTC
| Version 	| Platform 				| Topic 	|
|---------	|---------------------------	|-------	|
| v1.15.0 	| Win10 v2004b19041.329	| savetap	|

No matter what is used as the savetap address, the BASIC listing always contains:
_CLEAR 24063_ and _RANDOMIZE USR VAL "24064"_

Though the code is actually placed at the correct address and executed.
 
After the code has run and it returns to BASIC, it displays:
_C Nonsense in BASIC, 3456:1_
Just after the listing, there's a number displayed at the end. BASIC commands like LIST result in unexpected behaviour such as showing the same line repeating.

The same happens in Fuse 1.5.7 and SpecEmu 3.1b130220

```
	device zxspectrum48

	org 32000

begin:
	ret

	savetap "sjasmplus_savetap-test.tap",begin

```

**Comment by ped7g** [comment] 2020-06-12 06:33
Well, that snapshot-like `savetap` variant is meant more like "take over machine" for game/demo-like SW and other common usage of assembly on ZX, so the state of the BASIC was probably not considered at all for this feature, as usually one does not need BASIC for anything and never returns to it.

I guess it may be improved somewhat to me be more "correct" in a case like yours.

But overall it didn't receive any attention in recent versions and it's in the state as it was since early days of sjasmplus, as most of contributors to this fork don't use it, we prefer to produce non-snapshot like original tap files with each block designed by us (using the other variants of `savetap` to operate individual blocks). There were even some discussions about obsoleting it and removing it eventually, if it rots too much. But from your report it seems it still works probably as designed.

Do you have some particular use case on mind (to relate to, if somebody will work on improving this), what is important for you to get fixed?

**Comment by TheStruggleForAntiSpaghetti** [comment] 2020-06-12 16:39
But I must say that I don't have that much experience with sjasmplus and possible options to work smarter.

I frequently use `savetap` for easy testing in combination with BASIC, without having to set up a compile-chain with sjasmplus exporting a .bin and then:
- mktap.exe to convert a .bas to .tap
- bintap.exe to convert the .bin to a .tap
- combine the 2 .taps
which can then bu run with an emulator.

Two recent examples: a pt3 IM2 play routine that stays resident in BASIC and the FZX channel driver, which works when printed to #4, also from BASIC.
 
But if you have suggestions on alternative workflows and or options, that would be most welcome.
 
Is it possible to have sjasmplus compile a final tap including the BASIC loader and compiled code as in my example above?

**Comment by ped7g** [comment] 2020-06-12 23:42
well, this is unfortunately not as smooth ride as one may hope for, but it's also difficult to decide where to stop, as the assembler should IMHO focus on assembling things from assembly to machine code, so extensive ZX BASIC support feels wrong.

But without it is very difficult to produce BASIC loader if you are not familiar with ZX quite into depth.

You may check the [examples/TapLib](../blob/master/examples/TapLib) for simple BASIC loader written by Busy (maybe it will suit your needs or you can check how it is written), or continue to use the snapshot-like savetap (or even create SNA snapshots, I use those for quick prototyping with emulators before I write the proper build method to combine full tap file for final release).

I usually set up Makefile with all required steps and rules once the project grows beyond the initial prototype stage, so I set it up once and then it works.

Anyway... all that chit-chat above is about why this is not high priority bug for me (and probably most of the contributors on this branch). But it is still bug and valid report. So eventually this may get improved in future versions of sjasmplus, definitely thank you for reporting it and for the further examples of use cases.

**Comment by TheStruggleForAntiSpaghetti** [comment] 2020-06-13 05:58
I understand.
Thanks for your response and explanations.

**Comment by asdasd637** [comment] 2020-08-14 18:10
[[]()]()

**Comment by ped7g** [comment] 2021-03-08 03:06
Did some extra check of this, and I'm afraid the current CLEAR loader is designed to load as much RAM as possible by sacrificing BASIC compatibility, damaging the state of BASIC (expecting this feature to be used just to load machine code and take full control over machine).

I guess it is *possible* to create more advanced `savetap` recognizing there's enough room to provide less aggressive loader, which keeps BASIC in working state, but I'm personally not interested into writing one and make it build-in of sjasmplus, as you can supply all of this yourself (as SW author) by using the non-snapshot variants of `savetap`, saving individual blocks of data into the TAP file.

IMO it's better to keep this outside of sjasmplus binary, as it is easier to patch any such system in form of sources, like the mentioned examples/TapLib. When similar system becomes part of sjasmplus (like the current snapshot-like savetap variant), you have no chance to easily adjust it, except changing sources of sjasmplus itself.

So this is "won't fix" unless somebody actually wants to do it, but going by the discussion about currently active contributors to sjasmplus, most of us would actually like to remove this savetap feature, as generally shapshot-like TAP is not the recommended way to create new SW. (But I guess for less experienced ZX devs or quick prototyping it may be handy, so we are keeping it available, I myself tend to use `SAVESNA` a lot when quickly prototyping just few lines of code and checking it in emulators).

**Closed** 2024-08-13 15:03 UTC
Labels: bug, wontfix

**Comment by chad0x001** [comment] 2025-02-05 17:41
I'm having exactly the same issue. What did you find in the end to compile your .asm into a tap file you could play like you were loading from tape? I know sjasmplus is grat for making a .sna but I don't want that, I want to hear errrrr BLIP! errrrr BzzzBBBZZZZZbzzz etc. until the code is loaded and a simple basic proggy to run it

**Comment by TheStruggleForAntiSpaghetti** [comment] 2025-02-05 19:53
Hello, Chad.

I'm now creating my own BASIC loader.

BASICally, there are 2 ways to go about it:

1. Conversion of a text-file with your BASIC loader

- Use a text-file with your BASIC loader, compile that into a .tap file with tools like txt2bas or bas2tap.
- Add to this .tap file with consequent SAVETAP instructions.

Something like (in your main .asm):

```
	define fname "MyFabulousGame.tap"

; Compile BASIC loader text into a tap file
	IF ((_ERRORS = 0) && (_WARNINGS = 0))
		SHELLEXEC "call npx txt2bas -f tap -A 10 -i BASICLoader.bas -o ", fname
	ENDIF


; *** Loading screen ***
	org 16384
loadingscr_start:
	incbin "LoadingScreen.scr"
loadingscr_end:

; Add the loading screen to the tap file
	SAVETAP fname,CODE,"LScreen$",loadingscr_start, loadingscr_end - loadingscr_start
```

2. Build the loader with the BasicLib.asm by BusySoft that is included in the SJASMPlus distribution in the folder  _SJASMPlus\examples\BasicLib_
