### ISSUE TITLE
Order of definition critical for Next hardware IM2 vector table macro instantiation.

### ISSUE THREAD

**Issue by OnceBitten** [z00m128/sjasmplus#243] opened 2024-09-26 08:54 UTC
v1.20.3,  order-of-definition effect.

In a submodule called `Next.HardwareIM2` the macro `NEXT_HARDWARE_IM2_INTERRUPT_VECTOR_TABLE` is defined:

```
 MODULE HardwareIM2

default_interrupt_handler:
  ei
  reti

  STRUCT InterruptVectorTable                   ; In descending order of priority:
handler_line     WORD default_interrupt_handler ;  0 = Line interrupt (highest priority)
handler_UART0_Rx WORD default_interrupt_handler ;  1 = UART0 Rx
handler_UART1_Rx WORD default_interrupt_handler ;  2 = UART1 Rx
handler_CTC0     WORD default_interrupt_handler ;  3 = CTC channel 0
handler_CTC1     WORD default_interrupt_handler ;  4 = CTC channel 1
handler_CTC2     WORD default_interrupt_handler ;  5 = CTC channel 2
handler_CTC3     WORD default_interrupt_handler ;  6 = CTC channel 3
handler_CTC4     WORD default_interrupt_handler ;  7 = CTC channel 4
handler_CTC5     WORD default_interrupt_handler ;  8 = CTC channel 5
handler_CTC6     WORD default_interrupt_handler ;  9 = CTC channel 6
handler_CTC7     WORD default_interrupt_handler ; 10 = CTC channel 7
handler_ULA      WORD default_interrupt_handler ; 11 = ULA
handler_UART0_Tx WORD default_interrupt_handler ; 12 = UART0 Tx
handler_UART1_Tx WORD default_interrupt_handler ; 13 = UART1 Tx
handler_14       WORD default_interrupt_handler ; unused
handler_15       WORD default_interrupt_handler ; unused
  ENDS

  MACRO NEXT_HARDWARE_IM2_INTERRUPT_VECTOR_TABLE
  ALIGN 32, 0
interrupt_vector_table: Next.HardwareIM2.InterruptVectorTable
  ENDM

  ENDMODULE ; HardwareIM2`
```
In another module in another file there is the following initialisation code:
```
;  NEXT_HARDWARE_IM2_INTERRUPT_VECTOR_TABLE

initialise_hardware_IM2:
  nextreg Next.INTERRUPT_CONTROL,      ((low interrupt_vector_table) & %111000000) or %000'0'0'000'1
  nextreg Next.INTERRUPT_ENABLE_0,     %1'00000'0'1 ; enable expansion bus INT and ULA interrupts
                                                    ; disable line interrupt
  nextreg Next.INTERRUPT_ENABLE_1,     %00000000    ; disable all CTC channel interrupts
  nextreg Next.INTERRUPT_ENABLE_2,     %00000000    ; disable all UART0 and UART1 interrupts
  nextreg Next.DMA_INTERRUPT_ENABLE_0, %000000'0'1  ; enable ULA interrupting DMA
                                                    ; disable line interrupting DMA
  nextreg Next.DMA_INTERRUPT_ENABLE_1, %00000000    ; disable all CTC channels interrupting DMA
  nextreg Next.DMA_INTERRUPT_ENABLE_2, %00000000    ; disable UART0 and UART1 interrupting DMA

  ld A, high interrupt_vector_table
  ld I, A
  im 2
  ei
  ret

  NEXT_HARDWARE_IM2_INTERRUPT_VECTOR_TABLE
```

This code works. However, if I comment-out the macro instance and uncomment the one preceding the `initialise_hardware_IM2` label, it does not. Behaviour is then unpredictable, with screen corruption sometimes occurring, perhaps due to a faulty vector table. Apologies if I am missing my own mistake here.

**Comment by ped7g** [comment] 2024-09-27 14:38
By reading the source code I don't see anything suspicious. Can you provide for example two .nex files (working vs failing) with only this change, so I can first try to debug it in CSpect (I hope this works in CSpect) and see what is the root cause of the issue. (if the content is something you want to hide, maybe send direct email or send me files over ZXNext discord (Ped7g), or try to comment out as much as possible to keep only the unwanted behaviour and add files here. TY.

**Comment by OnceBitten** [comment] 2024-09-28 09:26
Hi ped7g, Thank you for responding and reformatting my post. My experimentation has grown too big and rambling to make a good bug example now. I think it is best over the next few weeks, when I have time, to excise all irrelevant parts and try to get the code behind the OK and bugged instances as small as possible. This code should only differ in the two cases by the un-commenting and re-commenting of the macro as above. The cause may be of my own making elsewhere, but the change seems so harmless superficially.

**Comment by ped7g** [comment] 2024-09-28 13:20
exactly, from the piece you posted I don't see any possible issue, so it's either some very subtle typo-like detail I missed or something else is failing in the parts you didn't post yet. I will close this for now, feel free to reopen when you have more complete examples of failing/working cases. Having two .nex files with full source is best way for me to replicate issue here, but I understand people don't want to post WIP of their projects. :)

**Closed by ped7g** 2024-09-28 13:20 UTC
Labels: bug, RFC

**Comment by OnceBitten** [comment] 2024-09-30 09:56
Hi Peter,

My name is Steve Thomas, aka OnceBitten on GitHub. I have now stripped the code down and amalgamated it into one file, and have located the problem. It was the following line in initialise_hardware_IM2:

  nextreg Next.INTERRUPT_CONTROL,  ((low interrupt_vector_table) & %111000000) or %000'0'0'000'1

The mask should be %11100000.The other binary constant is incorrectly 9-bits too, but it is harmless in this case. So as you suggested a subtle typo. I located the problem by using a DS pseudo-op before the vector table instantiation and discovered using the lbl file that the code worked when the table was assembled at 222:0040 but not at 222:0020.

I shall define labels for this sort of constant in the future, and check the definitions carefully. My apologies again, as the problem was with my code, not any part of the toolchain. Also, please may I offer belated thanks to you for offering to debug this. I appreciate your offer here, but you will be relieved to know that I will do my own debugging: I genuinely thought that there was a toolchain problem. There is the question, I suppose, of whether sjasmplus should warn if 9-bit numbers are used in an expression for an 8-bit immediate, but this would involve a basic kind of type system for expressions, and besides there are perhaps legitimate uses.

Kind regards,

Steve Thomas

On 28 Sep 2024, at 14:21, Peter Ped Helcmanovsky ***@***.******@***.***>> wrote:



exactly, from the piece you posted I don't see any possible issue, so it's either some very subtle typo-like detail I missed or something else is failing in the parts you didn't post yet. I will close this for now, feel free to reopen when you have more complete examples of failing/working cases. Having two .nex files with full source is best way for me to replicate issue here, but I understand people don't want to post WIP of their projects. :)

**Comment by OnceBitten** [comment] 2024-09-30 14:26
Thank you, Peter, for this information. I will familiarise myself with listing files ASAP.

On 30 Sep 2024, at 15:12, Peter Ped Helcmanovsky ***@***.******@***.***>> wrote:



I thought I did check that masking constant, but I guess I did read it wrongly in the end.

About warning: the expression evaluator is 32bit internally and that's intended, so expression like 1<<44 will overflow and produce undefined result (most likely 0).

But if you try to use resulting value as 8 bit value and it is above 255 or below -128, you will get truncation warning. In your case you prevented it by using low operator doing the masking sort of twice making it impossible to get value over 255.

If you would use only your explicit mask like (interrupt_vector_table & %111000000) or %000'0'0'000'1 - which should still produce only 8bit value after fixing the constants, you would get truncation warning for every other 256 byte page because of the 9th bit being 1 for those high bytes of interrupt_vector_table address. But that does mean you could still end with wrong code and without warning, so that would give you just 50% chance to catch the typo in mask earlier.

When you suspect toolchain problem, check also the listing file, where you can see also machine code bytes and their address position in memory. Also don't hesitate to open github issue here in case you can't figure it out yourself, it's no big deal even if it turns out to be issue in the source code and not toolchain.
