### ISSUE TITLE
Not everything works after return from snapshot to Basic

### ISSUE THREAD

**Issue by chupocro** [z00m128/sjasmplus#215] opened 2023-07-21 02:54 UTC
I added `EI` before `RET` and return from snapshot to Basic works well but if I then try to run the same program again with `RANDOMIZE USR 49152` nothing happens - interpreter just ignores the `ENTER` key. On the other hand, `RANDOMIZE USR 0` does work. Here is the test program:

```
            device zxspectrum48

            org #c000
start       ld hl,16384
            ld d,h
            ld e,l
            inc e
            ld bc,6143
            ld (hl),255
            ldir
            ei
            ret
end
            display " "
            display "Program length: ", /a, end - start, " bytes"
            display " "
            savesna "ret_to_basic.sna", start
```

Seems as after running such a snapshot RANDOMIZE USR works with only small numbers as argument. Maybe it has something with RAMTOP or some other System variables not set? As I can see from the source IY is set to 0x5c3a so that isn't a problem.

There must be a way to return from the snapshot to a working Spectrum.

**Comment by ped7g** [comment] 2023-07-21 16:07
without trying to reproduce/investigate:

try `device zxspectrum48,29999` for example (RAMTOP = 29999), the default ramtop is 0x5D5B (23899) which may be too low for BASIC stuff working maybe. If the explicit [higher] ramtop helps, consider this "by design" and close it. :)

**Comment by chupocro** [comment] 2023-07-21 22:24
Yes, that was it, thank you very much!! :-) I didn't thought of that. I'd expect `4 Out of memory` in case there isn't room enough for the Basic command but the error is not displayed even if I try to enter `RANDOMIZE USR 49152` as a Basic line :-/

So to recreate the state as similar to the state of the original Spcetrum with bytes from the snapshot loaded into RAM the directive should be `device zxspectrum48,0xff57`

**Closed** 2023-07-21 22:27 UTC
