### ISSUE TITLE
There is no <warning-id> for %some error/warning%

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [z00m128/sjasmplus#179] opened 2022-05-09 02:37 UTC
1.19.0 - error: Forward reference

**Comment by ped7g** [comment] 2022-05-09 08:45
that looks like `defl` expression with forward reference? That's not a warning, that's error. `defl`/`=` are variable-like symbols, which can be redefined at any point of source, and their actual value is important, so they can't forward-reference other symbol. Use `equ` or reorganise source to avoid forward reference.

Also warnings without ID are like "hard" warnings, almost errors, they should mark source which is actually wrong and needs fixing. Without providing particular example where you have warning on fully valid source the discussion is moot...

**Comment by NEO-SPECTRUMAN** [comment] 2022-05-10 03:25
Ok 
i'll try to isolate/localize it later..

**Comment by NEO-SPECTRUMAN** [comment] 2022-05-12 05:12
warning: Label has different value in pass 3: previous value xxx not equal xxx

**Comment by NEO-SPECTRUMAN** [comment] 2022-05-12 07:56
also separated prefixes with some "holes"
is would be useful too

prefix
some unstable data
prefix
some unstable data
destination addr

**Comment by ped7g** [comment] 2022-05-12 08:10
:man_shrugging:  if you see "different value in pass 3" warning, you are doing it 'wrong" (not as it was meant to be used). If it works for you, good for you, but you are really beyond the limit and on your own.

**Comment by NEO-SPECTRUMAN** [comment] 2022-05-12 08:13
there is no pass 4 pass 7
for doung it not wrong

**Comment by NEO-SPECTRUMAN** [comment] 2022-05-12 08:21
also
what about saving
full labels variables lua variables arrays etc
in file

for load in new "pass1\2\3" asm files?

**Comment by ped7g** [comment] 2022-05-12 08:37
I'm afraid I don't fully understand. symbols are "global" and lua context is "global", above passes. The source code expansion (substitution done by DEFINE/macro) is reset per pass. So saving lua variables or labels per-pass doesn't make sense to me, as they exist outside of passes (and purpose of passes is to refine the symbol values so in last pass all symbols have correct value).

example:
```
  LUA PASS1
    debug_info_cnt = 0
    function debug_info()
      debug_info_cnt = debug_info_cnt + 1
      print("pass "..sj.get_define("__PASS__").." line "..sj.get_define("__LINE__").." xxx="..sj.get_label("xxx")..
          " (debug info called "..debug_info_cnt.." times)")
    end
  ENDLUA
  LUA ALLPASS
    debug_info()
  ENDLUA
  IFDEF DO_IT : DISPLAY "never" : ENDIF
  DEFINE DO_IT 1
  IFDEF DO_IT : DISPLAY "pass ",/A,__PASS__," display, xxx = ",/A,xxx : ENDIF
  DB 1
xxx:
  LUA ALLPASS
    debug_info()
  ENDLUA
```
output:
```
$ sjasmplus temp2.asm 
SjASMPlus Z80 Cross-Assembler v1.19.0 (https://github.com/z00m128/sjasmplus)
pass 1 line 11 xxx=0 (debug info called 1 times)
pass 1 line 19 xxx=1 (debug info called 2 times)
Pass 1 complete (0 errors)
pass 2 line 11 xxx=1 (debug info called 3 times)
pass 2 line 19 xxx=1 (debug info called 4 times)
Pass 2 complete (0 errors)
pass 3 line 11 xxx=1 (debug info called 5 times)
> pass 0x0003, 3 display, xxx = 0x0001, 1
pass 3 line 19 xxx=1 (debug info called 6 times)
Pass 3 complete
Errors: 0, warnings: 0, compiled: 18 lines, work time: 0.002 seconds
```
so as you can see, the lua variable `debug_info_cnt` or label `xxx` exists across passes, the `DO_IT` define gets reset ahead of every pass (so the "never" IFDEF is never true).

**Comment by ped7g** [comment] 2022-05-12 08:41
if you would modify the example to do instead of `DB 1` -> `DS xxx+1`, it will break the "xxx" value in last pass, as it will keep moving it in every pass, so pass2 differs from pass3 and different parts of source assemble with different "xxx" value in last pass.

**Comment by ped7g** [comment] 2023-02-12 00:48
closing this as two possible actions (changing to N-pass and improving docs about 3-pass architecture) are already open in other issues, and the rest of this seems to be working by design and/or lacking more detailed information.

**Closed by ped7g** 2023-02-12 00:48 UTC
Labels: enhancement
